### ISSUE TITLE
LMM compilation error list: "go to" button does not work in Ubuntu 18.04

### ISSUE THREAD

**Issue by MCP1** [marcov64/Lsd#5]
Nothing happens when the button is clicked and an error is selected.

**Comment by MCP1** [comment]
Cannot reproduce it in my Ubuntu 18.04 computer, would need more details on how to reproduce the problem.

**Comment by MCP1** [comment]
Improved the error message handling, hope it fixed this problem which I cannot reproduce.
